// This file is @generated by prost-build.
/// SKU 元数据
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GoodsSkuMeta {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "2")]
    pub items: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// 商品参数
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GoodsArgument {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub value: ::prost::alloc::string::String,
}
/// 商品
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Goods {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    /// 店铺
    #[prost(string, tag = "2")]
    pub shop_id: ::prost::alloc::string::String,
    /// 是否虚拟商品
    #[prost(bool, tag = "3")]
    pub is_vir: bool,
    /// 分类
    #[prost(string, tag = "4")]
    pub category_id: ::prost::alloc::string::String,
    /// 名称
    #[prost(string, tag = "5")]
    pub name: ::prost::alloc::string::String,
    /// 图片
    #[prost(string, repeated, tag = "6")]
    pub images: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// 状态
    #[prost(enumeration = "GoodsStatus", tag = "7")]
    pub status: i32,
    /// 详情
    #[prost(string, tag = "8")]
    pub detail: ::prost::alloc::string::String,
    /// 评论需要审核
    #[prost(bool, tag = "9")]
    pub comment_need_audit: bool,
    /// 服务保障
    #[prost(string, repeated, tag = "10")]
    pub service_guarantee: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// 标签
    #[prost(string, repeated, tag = "11")]
    pub tags: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// 参数
    #[prost(message, repeated, tag = "12")]
    pub arguments: ::prost::alloc::vec::Vec<GoodsArgument>,
    /// 总库存
    #[prost(int64, tag = "13")]
    pub stock: i64,
    /// 总销量
    #[prost(int64, tag = "14")]
    pub sales: i64,
    /// sku
    #[prost(message, repeated, tag = "15")]
    pub sku_meta: ::prost::alloc::vec::Vec<GoodsSkuMeta>,
    /// 运费
    #[prost(int32, tag = "16")]
    pub fare: i32,
    /// 商品推荐
    #[prost(string, repeated, tag = "17")]
    pub recommendations: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(message, optional, tag = "18")]
    pub created_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag = "19")]
    pub updated_at: ::core::option::Option<::prost_types::Timestamp>,
}
/// 商品属性
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GoodsAttr {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    /// 商品
    #[prost(string, tag = "2")]
    pub goods_id: ::prost::alloc::string::String,
    /// sku
    #[prost(string, repeated, tag = "3")]
    pub sku_arr: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// 库存
    #[prost(int64, tag = "4")]
    pub stock: i64,
    /// 价格
    #[prost(int64, tag = "5")]
    pub price: i64,
    /// 销量
    #[prost(int64, tag = "6")]
    pub sales: i64,
    /// 编号
    #[prost(string, tag = "7")]
    pub code: ::prost::alloc::string::String,
    /// 条码
    #[prost(string, tag = "8")]
    pub bar_code: ::prost::alloc::string::String,
    /// 体积（cm3）
    #[prost(int32, tag = "9")]
    pub volume: i32,
    /// 重量（kg）
    #[prost(int32, tag = "10")]
    pub weight: i32,
}
/// 商品评论
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GoodsComment {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    /// 商品
    #[prost(string, tag = "2")]
    pub goods_id: ::prost::alloc::string::String,
    /// 商品名称（含规格）
    #[prost(string, tag = "3")]
    pub goods_full_name: ::prost::alloc::string::String,
    /// 是否商家自评
    #[prost(bool, tag = "4")]
    pub is_self: bool,
    /// 用户（商家自评时，为空）
    #[prost(string, tag = "5")]
    pub user_id: ::prost::alloc::string::String,
    /// 用户头像（商家自评时，可以杜撰）
    #[prost(string, tag = "6")]
    pub user_avatar: ::prost::alloc::string::String,
    /// 用户昵称（商家自评时，可以杜撰）
    #[prost(string, tag = "7")]
    pub user_nickname: ::prost::alloc::string::String,
    /// 内容
    #[prost(string, tag = "8")]
    pub content: ::prost::alloc::string::String,
    /// 商品评分
    #[prost(int32, tag = "9")]
    pub goods_star: i32,
    /// 服务评分
    #[prost(int32, tag = "10")]
    pub service_star: i32,
    /// 图片
    #[prost(string, repeated, tag = "11")]
    pub images: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(message, optional, tag = "12")]
    pub created_at: ::core::option::Option<::prost_types::Timestamp>,
}
/// 商品状态
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum GoodsStatus {
    /// 上架
    Available = 0,
    /// 下架
    Unavailable = 1,
}
impl GoodsStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Available => "Available",
            Self::Unavailable => "Unavailable",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "Available" => Some(Self::Available),
            "Unavailable" => Some(Self::Unavailable),
            _ => None,
        }
    }
}
