// This file is @generated by prost-build.
/// 账单消息
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Invoice {
    /// 账单唯一 ID (CHAR(20))
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    /// 关联的业务 ID (通常是订单 ID)
    #[prost(string, tag = "2")]
    pub order_id: ::prost::alloc::string::String,
    /// 买家 ID
    #[prost(string, tag = "3")]
    pub user_id: ::prost::alloc::string::String,
    /// 卖家店铺 ID
    #[prost(string, tag = "4")]
    pub shop_id: ::prost::alloc::string::String,
    /// 应付金额 (单位：分)
    #[prost(int64, tag = "5")]
    pub amount: i64,
    /// 实付金额 (单位：分)
    #[prost(int64, tag = "6")]
    pub pay_amount: i64,
    /// 状态
    #[prost(enumeration = "InvoiceStatus", tag = "7")]
    pub status: i32,
    /// 类型
    #[prost(enumeration = "InvoiceKind", tag = "8")]
    pub kind: i32,
    /// 支付交易号
    #[prost(string, tag = "9")]
    pub pay_tx_id: ::prost::alloc::string::String,
    /// 备注
    #[prost(string, tag = "10")]
    pub remark: ::prost::alloc::string::String,
    /// 截止支付日期
    #[prost(message, optional, tag = "11")]
    pub due_date: ::core::option::Option<::prost_types::Timestamp>,
    /// 支付时间
    #[prost(message, optional, tag = "12")]
    pub paid_at: ::core::option::Option<::prost_types::Timestamp>,
    /// 创建时间
    #[prost(message, optional, tag = "13")]
    pub created_at: ::core::option::Option<::prost_types::Timestamp>,
    /// 更新时间
    #[prost(message, optional, tag = "14")]
    pub updated_at: ::core::option::Option<::prost_types::Timestamp>,
}
/// 账单状态枚举
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum InvoiceStatus {
    /// 待支付
    Unpaid = 0,
    /// 已支付
    Paid = 1,
    /// 已逾期
    Overdue = 2,
    /// 已取消
    Cancelled = 3,
    /// 已退款
    Refunded = 4,
}
impl InvoiceStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unpaid => "Unpaid",
            Self::Paid => "Paid",
            Self::Overdue => "Overdue",
            Self::Cancelled => "Cancelled",
            Self::Refunded => "Refunded",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "Unpaid" => Some(Self::Unpaid),
            "Paid" => Some(Self::Paid),
            "Overdue" => Some(Self::Overdue),
            "Cancelled" => Some(Self::Cancelled),
            "Refunded" => Some(Self::Refunded),
            _ => None,
        }
    }
}
/// 账单类型枚举
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum InvoiceKind {
    /// 订单支付
    OrderPayment = 0,
    /// 订单退款
    OrderRefund = 1,
    /// 提现
    Withdrawal = 2,
    /// 充值
    Recharge = 3,
    /// 佣金/分成
    Commission = 4,
    /// 平台服务费
    PlatformService = 5,
}
impl InvoiceKind {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::OrderPayment => "OrderPayment",
            Self::OrderRefund => "OrderRefund",
            Self::Withdrawal => "Withdrawal",
            Self::Recharge => "Recharge",
            Self::Commission => "Commission",
            Self::PlatformService => "PlatformService",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "OrderPayment" => Some(Self::OrderPayment),
            "OrderRefund" => Some(Self::OrderRefund),
            "Withdrawal" => Some(Self::Withdrawal),
            "Recharge" => Some(Self::Recharge),
            "Commission" => Some(Self::Commission),
            "PlatformService" => Some(Self::PlatformService),
            _ => None,
        }
    }
}
/// 获取单条
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetReply {
    #[prost(message, optional, tag = "1")]
    pub invoice: ::core::option::Option<Invoice>,
}
/// 列表
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListRequest {
    #[prost(message, optional, tag = "1")]
    pub pr: ::core::option::Option<super::paginate::PaginateRequest>,
    #[prost(string, optional, tag = "2")]
    pub user_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "3")]
    pub order_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "4")]
    pub shop_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(enumeration = "InvoiceStatus", optional, tag = "5")]
    pub status: ::core::option::Option<i32>,
    #[prost(enumeration = "InvoiceKind", optional, tag = "6")]
    pub kind: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "7")]
    pub pay_tx_id: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListReply {
    #[prost(message, optional, tag = "1")]
    pub paginate: ::core::option::Option<super::paginate::Paginate>,
    #[prost(message, repeated, tag = "2")]
    pub invoices: ::prost::alloc::vec::Vec<Invoice>,
}
/// 修改状态
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateStatusRequest {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(enumeration = "InvoiceStatus", tag = "2")]
    pub status: i32,
}
/// Generated client implementations.
pub mod invoice_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct InvoiceServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl InvoiceServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> InvoiceServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InvoiceServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            InvoiceServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// 创建
        pub async fn create(
            &mut self,
            request: impl tonic::IntoRequest<super::Invoice>,
        ) -> std::result::Result<
            tonic::Response<super::super::resp::IdReply>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/invoice.InvoiceService/Create",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("invoice.InvoiceService", "Create"));
            self.inner.unary(req, path, codec).await
        }
        /// 获取单条
        pub async fn get(
            &mut self,
            request: impl tonic::IntoRequest<super::super::req::IdRequest>,
        ) -> std::result::Result<tonic::Response<super::GetReply>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/invoice.InvoiceService/Get",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("invoice.InvoiceService", "Get"));
            self.inner.unary(req, path, codec).await
        }
        /// 列表
        pub async fn list(
            &mut self,
            request: impl tonic::IntoRequest<super::ListRequest>,
        ) -> std::result::Result<tonic::Response<super::ListReply>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/invoice.InvoiceService/List",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("invoice.InvoiceService", "List"));
            self.inner.unary(req, path, codec).await
        }
        /// 修改状态
        pub async fn update_status(
            &mut self,
            request: impl tonic::IntoRequest<super::UpdateStatusRequest>,
        ) -> std::result::Result<
            tonic::Response<super::super::resp::AffReply>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/invoice.InvoiceService/UpdateStatus",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("invoice.InvoiceService", "UpdateStatus"));
            self.inner.unary(req, path, codec).await
        }
        /// 完成支付
        pub async fn complete_paid(
            &mut self,
            request: impl tonic::IntoRequest<super::super::req::IdRequest>,
        ) -> std::result::Result<
            tonic::Response<super::super::resp::AffReply>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/invoice.InvoiceService/CompletePaid",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("invoice.InvoiceService", "CompletePaid"));
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod invoice_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with InvoiceServiceServer.
    #[async_trait]
    pub trait InvoiceService: std::marker::Send + std::marker::Sync + 'static {
        /// 创建
        async fn create(
            &self,
            request: tonic::Request<super::Invoice>,
        ) -> std::result::Result<
            tonic::Response<super::super::resp::IdReply>,
            tonic::Status,
        >;
        /// 获取单条
        async fn get(
            &self,
            request: tonic::Request<super::super::req::IdRequest>,
        ) -> std::result::Result<tonic::Response<super::GetReply>, tonic::Status>;
        /// 列表
        async fn list(
            &self,
            request: tonic::Request<super::ListRequest>,
        ) -> std::result::Result<tonic::Response<super::ListReply>, tonic::Status>;
        /// 修改状态
        async fn update_status(
            &self,
            request: tonic::Request<super::UpdateStatusRequest>,
        ) -> std::result::Result<
            tonic::Response<super::super::resp::AffReply>,
            tonic::Status,
        >;
        /// 完成支付
        async fn complete_paid(
            &self,
            request: tonic::Request<super::super::req::IdRequest>,
        ) -> std::result::Result<
            tonic::Response<super::super::resp::AffReply>,
            tonic::Status,
        >;
    }
    #[derive(Debug)]
    pub struct InvoiceServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> InvoiceServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for InvoiceServiceServer<T>
    where
        T: InvoiceService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/invoice.InvoiceService/Create" => {
                    #[allow(non_camel_case_types)]
                    struct CreateSvc<T: InvoiceService>(pub Arc<T>);
                    impl<T: InvoiceService> tonic::server::UnaryService<super::Invoice>
                    for CreateSvc<T> {
                        type Response = super::super::resp::IdReply;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::Invoice>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as InvoiceService>::create(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = CreateSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/invoice.InvoiceService/Get" => {
                    #[allow(non_camel_case_types)]
                    struct GetSvc<T: InvoiceService>(pub Arc<T>);
                    impl<
                        T: InvoiceService,
                    > tonic::server::UnaryService<super::super::req::IdRequest>
                    for GetSvc<T> {
                        type Response = super::GetReply;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::super::req::IdRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as InvoiceService>::get(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/invoice.InvoiceService/List" => {
                    #[allow(non_camel_case_types)]
                    struct ListSvc<T: InvoiceService>(pub Arc<T>);
                    impl<
                        T: InvoiceService,
                    > tonic::server::UnaryService<super::ListRequest> for ListSvc<T> {
                        type Response = super::ListReply;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ListRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as InvoiceService>::list(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ListSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/invoice.InvoiceService/UpdateStatus" => {
                    #[allow(non_camel_case_types)]
                    struct UpdateStatusSvc<T: InvoiceService>(pub Arc<T>);
                    impl<
                        T: InvoiceService,
                    > tonic::server::UnaryService<super::UpdateStatusRequest>
                    for UpdateStatusSvc<T> {
                        type Response = super::super::resp::AffReply;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::UpdateStatusRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as InvoiceService>::update_status(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = UpdateStatusSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/invoice.InvoiceService/CompletePaid" => {
                    #[allow(non_camel_case_types)]
                    struct CompletePaidSvc<T: InvoiceService>(pub Arc<T>);
                    impl<
                        T: InvoiceService,
                    > tonic::server::UnaryService<super::super::req::IdRequest>
                    for CompletePaidSvc<T> {
                        type Response = super::super::resp::AffReply;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::super::req::IdRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as InvoiceService>::complete_paid(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = CompletePaidSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for InvoiceServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "invoice.InvoiceService";
    impl<T> tonic::server::NamedService for InvoiceServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
