// This file is @generated by prost-build.
/// 商家
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Merchant {
    /// 唯一标识符 (Rust 中的 id 通常对应数据库的主键)
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    /// 商户名称
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    /// 简称
    #[prost(string, tag = "3")]
    pub short_name: ::prost::alloc::string::String,
    /// 状态 (对应 audit::AuditStatus)
    #[prost(enumeration = "super::audit::AuditStatus", tag = "4")]
    pub status: i32,
    /// 类型 (对应 MerchantKind)
    #[prost(enumeration = "MerchantKind", tag = "5")]
    pub kind: i32,
    /// 创建时间
    #[prost(message, optional, tag = "6")]
    pub created_at: ::core::option::Option<::prost_types::Timestamp>,
    /// 元数据 (在 Rust 中是 Json<MerchantMeta>)
    /// 在 Protobuf 中直接嵌套 Message 是最佳实践
    #[prost(message, optional, tag = "7")]
    pub meta: ::core::option::Option<MerchantMeta>,
}
/// 定义照片对，用于替换 Rust 中的 (String, String)
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ImagePair {
    /// 正面
    #[prost(string, tag = "1")]
    pub front_url: ::prost::alloc::string::String,
    /// 反面
    #[prost(string, tag = "2")]
    pub back_url: ::prost::alloc::string::String,
}
/// 商家元数据
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MerchantMeta {
    /// 营业执照(照片)
    #[prost(string, optional, tag = "1")]
    pub business_license: ::core::option::Option<::prost::alloc::string::String>,
    /// 证件注册号/统一社会信用代码
    #[prost(string, optional, tag = "2")]
    pub business_license_number: ::core::option::Option<::prost::alloc::string::String>,
    /// 商户名称
    #[prost(string, optional, tag = "3")]
    pub name: ::core::option::Option<::prost::alloc::string::String>,
    /// 商户简称
    #[prost(string, optional, tag = "4")]
    pub short_name: ::core::option::Option<::prost::alloc::string::String>,
    /// 经营者/法定代表人姓名
    #[prost(string, optional, tag = "5")]
    pub legal_representative_name: ::core::option::Option<
        ::prost::alloc::string::String,
    >,
    /// 营业期限
    #[prost(message, optional, tag = "6")]
    pub business_license_expiry_date: ::core::option::Option<::prost_types::Timestamp>,
    /// 注册地址
    #[prost(string, optional, tag = "7")]
    pub registered_address: ::core::option::Option<::prost::alloc::string::String>,
    /// 经营者/法人身份证/护照照片（正反面）
    #[prost(message, optional, tag = "8")]
    pub legal_representative_id_pic: ::core::option::Option<ImagePair>,
    /// 法人身份证姓名
    #[prost(string, optional, tag = "9")]
    pub legal_representative_id_name: ::core::option::Option<
        ::prost::alloc::string::String,
    >,
    /// 法人身份证号
    #[prost(string, optional, tag = "10")]
    pub legal_representative_id_number: ::core::option::Option<
        ::prost::alloc::string::String,
    >,
    /// 法人身份证有效期
    #[prost(message, optional, tag = "11")]
    pub legal_representative_id_expiry_date: ::core::option::Option<
        super::range::DateRange,
    >,
    /// 法人身份证地址
    #[prost(string, optional, tag = "12")]
    pub legal_representative_id_address: ::core::option::Option<
        ::prost::alloc::string::String,
    >,
    /// 账户地址(web3钱包地址)
    #[prost(string, optional, tag = "13")]
    pub account_address: ::core::option::Option<::prost::alloc::string::String>,
    /// 超级管理员类型,是否是法人(经营者/法人, 经办人)
    #[prost(bool, optional, tag = "14")]
    pub super_admin_is_legal_representative: ::core::option::Option<bool>,
    /// 超级管理员(如果是经办人)身份证/护照照片(正反面)
    #[prost(message, optional, tag = "15")]
    pub super_admin_id_pic: ::core::option::Option<ImagePair>,
    /// 超级管理员(如果是经办人)身份证有效期
    #[prost(message, optional, tag = "16")]
    pub super_admin_id_expiry_date: ::core::option::Option<super::range::DateRange>,
    /// 超级管理员身份证姓名
    #[prost(string, optional, tag = "17")]
    pub super_admin_id_name: ::core::option::Option<::prost::alloc::string::String>,
    /// 超级管理员身份证号
    #[prost(string, optional, tag = "18")]
    pub super_admin_id_number: ::core::option::Option<::prost::alloc::string::String>,
    /// 超级管理员手机号码
    #[prost(string, optional, tag = "19")]
    pub super_admin_phone: ::core::option::Option<::prost::alloc::string::String>,
    /// 超级管理员邮箱
    #[prost(string, optional, tag = "20")]
    pub super_admin_email: ::core::option::Option<::prost::alloc::string::String>,
    /// 特殊资质（照片，0~5张）
    #[prost(string, repeated, tag = "21")]
    pub special_qualification_pics: ::prost::alloc::vec::Vec<
        ::prost::alloc::string::String,
    >,
    /// 补充材料（照片，0~5张）
    #[prost(string, repeated, tag = "22")]
    pub supplementary_material_pics: ::prost::alloc::vec::Vec<
        ::prost::alloc::string::String,
    >,
    /// 补充说明（0~500个字）
    #[prost(string, optional, tag = "23")]
    pub supplementary_explain: ::core::option::Option<::prost::alloc::string::String>,
}
/// 商家账号
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MerchantAccount {
    /// 账号唯一 ID
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    /// 关联的商家 ID
    #[prost(string, tag = "2")]
    pub merchant_id: ::prost::alloc::string::String,
    /// 登录邮箱
    #[prost(string, tag = "3")]
    pub email: ::prost::alloc::string::String,
    /// 密码 (注意：建议仅在内部认证服务间使用，对外 API 建议忽略此字段)
    #[prost(string, tag = "4")]
    pub password: ::prost::alloc::string::String,
    /// 昵称
    #[prost(string, tag = "5")]
    pub nickname: ::prost::alloc::string::String,
    /// 是否为超级管理员
    #[prost(bool, tag = "6")]
    pub is_super: bool,
    /// 权限位 (Rust 中的 i64 对应 int64)
    /// 通常用于位运算权限控制
    #[prost(int64, tag = "7")]
    pub permission: i64,
    /// 创建时间
    #[prost(message, optional, tag = "8")]
    pub created_at: ::core::option::Option<::prost_types::Timestamp>,
}
/// 商家审核
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MerchantAudit {
    /// 审核记录唯一 ID
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    /// 关联的商家 ID
    #[prost(string, tag = "2")]
    pub merchant_id: ::prost::alloc::string::String,
    /// 审核员的 ID (通常对应后台管理员账号 ID)
    #[prost(string, tag = "3")]
    pub auditor_id: ::prost::alloc::string::String,
    /// 商家审核状态
    #[prost(enumeration = "super::audit::AuditStatus", tag = "4")]
    pub audit_status: i32,
    /// 审核的备注或意见 (例如拒绝原因)
    #[prost(string, tag = "5")]
    pub audit_comments: ::prost::alloc::string::String,
    /// 审核的时间
    #[prost(message, optional, tag = "6")]
    pub audit_date: ::core::option::Option<::prost_types::Timestamp>,
}
/// 商家类型
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum MerchantKind {
    /// 企业
    Enterprise = 0,
    /// 个体户
    SoleProprietorship = 1,
    /// 个人
    Individual = 2,
}
impl MerchantKind {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Enterprise => "Enterprise",
            Self::SoleProprietorship => "SoleProprietorship",
            Self::Individual => "Individual",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "Enterprise" => Some(Self::Enterprise),
            "SoleProprietorship" => Some(Self::SoleProprietorship),
            "Individual" => Some(Self::Individual),
            _ => None,
        }
    }
}
