// This file is @generated by prost-build.
/// 订单项快照
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OrderItemSnap {
    #[prost(string, tag = "1")]
    pub goods_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub shop_id: ::prost::alloc::string::String,
    #[prost(bool, tag = "3")]
    pub is_vir: bool,
    #[prost(string, tag = "4")]
    pub category_id: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "6")]
    pub images: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// 映射自 goods_status
    #[prost(enumeration = "super::goods::GoodsStatus", tag = "7")]
    pub status: i32,
    #[prost(string, tag = "8")]
    pub detail: ::prost::alloc::string::String,
    #[prost(bool, tag = "9")]
    pub comment_need_audit: bool,
    #[prost(string, repeated, tag = "10")]
    pub service_guarantee: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, repeated, tag = "11")]
    pub tags: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(message, repeated, tag = "12")]
    pub arguments: ::prost::alloc::vec::Vec<super::goods::GoodsArgument>,
    #[prost(message, repeated, tag = "13")]
    pub sku_meta: ::prost::alloc::vec::Vec<super::goods::GoodsSkuMeta>,
    #[prost(int32, tag = "14")]
    pub fare: i32,
    #[prost(string, repeated, tag = "15")]
    pub recommendations: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, tag = "16")]
    pub sku_id: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "17")]
    pub sku_arr: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, tag = "18")]
    pub goods_full_name: ::prost::alloc::string::String,
    #[prost(string, tag = "19")]
    pub goods_image: ::prost::alloc::string::String,
    #[prost(int64, tag = "20")]
    pub price: i64,
    #[prost(int64, tag = "21")]
    pub real_price: i64,
}
/// 订单主消息
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Order {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub shop_id: ::prost::alloc::string::String,
    #[prost(int64, tag = "4")]
    pub total_amount: i64,
    #[prost(int64, tag = "5")]
    pub pay_amount: i64,
    #[prost(int64, tag = "6")]
    pub freight_amount: i64,
    #[prost(enumeration = "OrderStatus", tag = "7")]
    pub status: i32,
    #[prost(enumeration = "PaymentMethod", tag = "8")]
    pub pay_method: i32,
    #[prost(string, tag = "9")]
    pub consignee_name: ::prost::alloc::string::String,
    #[prost(string, tag = "10")]
    pub consignee_phone: ::prost::alloc::string::String,
    #[prost(string, tag = "11")]
    pub consignee_address: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "12")]
    pub items: ::prost::alloc::vec::Vec<OrderItemSnap>,
    #[prost(message, repeated, tag = "13")]
    pub cart_items: ::prost::alloc::vec::Vec<super::cart::CartItem>,
    #[prost(message, optional, tag = "14")]
    pub pay_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag = "15")]
    pub ship_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag = "16")]
    pub completed_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag = "17")]
    pub created_at: ::core::option::Option<::prost_types::Timestamp>,
}
/// 订单状态
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum OrderStatus {
    PendingPayment = 0,
    PendingShipment = 1,
    Shipped = 2,
    Completed = 3,
    Cancelled = 4,
    Refunded = 5,
}
impl OrderStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::PendingPayment => "PendingPayment",
            Self::PendingShipment => "PendingShipment",
            Self::Shipped => "Shipped",
            Self::Completed => "Completed",
            Self::Cancelled => "Cancelled",
            Self::Refunded => "Refunded",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "PendingPayment" => Some(Self::PendingPayment),
            "PendingShipment" => Some(Self::PendingShipment),
            "Shipped" => Some(Self::Shipped),
            "Completed" => Some(Self::Completed),
            "Cancelled" => Some(Self::Cancelled),
            "Refunded" => Some(Self::Refunded),
            _ => None,
        }
    }
}
/// 支付方式
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum PaymentMethod {
    Web3 = 0,
    WechatPay = 1,
    Alipay = 2,
    Balance = 3,
    CreditCard = 4,
}
impl PaymentMethod {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Web3 => "Web3",
            Self::WechatPay => "WechatPay",
            Self::Alipay => "Alipay",
            Self::Balance => "Balance",
            Self::CreditCard => "CreditCard",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "Web3" => Some(Self::Web3),
            "WechatPay" => Some(Self::WechatPay),
            "Alipay" => Some(Self::Alipay),
            "Balance" => Some(Self::Balance),
            "CreditCard" => Some(Self::CreditCard),
            _ => None,
        }
    }
}
/// 获取单条
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetReply {
    #[prost(message, optional, tag = "1")]
    pub order: ::core::option::Option<Order>,
}
/// 列表
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListRequest {
    #[prost(message, optional, tag = "1")]
    pub pr: ::core::option::Option<super::paginate::PaginateRequest>,
    #[prost(string, optional, tag = "2")]
    pub user_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "3")]
    pub shop_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(enumeration = "OrderStatus", optional, tag = "4")]
    pub status: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "5")]
    pub consignee_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "6")]
    pub consignee_phone: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "7")]
    pub consignee_address: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "8")]
    pub goods_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "9")]
    pub goods_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "10")]
    pub sku_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "11")]
    pub sku_name: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListReply {
    #[prost(message, optional, tag = "1")]
    pub paginate: ::core::option::Option<super::paginate::Paginate>,
    #[prost(message, repeated, tag = "2")]
    pub orders: ::prost::alloc::vec::Vec<Order>,
}
/// 更新地址
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateAddressRequest {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub consignee_name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub consignee_phone: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub consignee_address: ::prost::alloc::string::String,
}
/// 更新状态
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateStatusRequest {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(enumeration = "OrderStatus", tag = "2")]
    pub status: i32,
}
/// 更新价格
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateAmountRequest {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(int64, tag = "2")]
    pub total_amount: i64,
    #[prost(int64, tag = "3")]
    pub freight_amount: i64,
}
/// 完成支付
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CompletePayRequest {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(int64, tag = "2")]
    pub pay_amount: i64,
}
/// Generated client implementations.
pub mod order_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct OrderServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl OrderServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> OrderServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> OrderServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            OrderServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// 创建
        pub async fn create(
            &mut self,
            request: impl tonic::IntoRequest<super::Order>,
        ) -> std::result::Result<
            tonic::Response<super::super::resp::IdReply>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/order.OrderService/Create",
            );
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new("order.OrderService", "Create"));
            self.inner.unary(req, path, codec).await
        }
        /// 获取单条
        pub async fn get(
            &mut self,
            request: impl tonic::IntoRequest<super::super::req::IdRequest>,
        ) -> std::result::Result<tonic::Response<super::GetReply>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/order.OrderService/Get");
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new("order.OrderService", "Get"));
            self.inner.unary(req, path, codec).await
        }
        /// 列表
        pub async fn list(
            &mut self,
            request: impl tonic::IntoRequest<super::ListRequest>,
        ) -> std::result::Result<tonic::Response<super::ListReply>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/order.OrderService/List");
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new("order.OrderService", "List"));
            self.inner.unary(req, path, codec).await
        }
        /// 更新地址
        pub async fn update_address(
            &mut self,
            request: impl tonic::IntoRequest<super::UpdateAddressRequest>,
        ) -> std::result::Result<
            tonic::Response<super::super::resp::AffReply>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/order.OrderService/UpdateAddress",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("order.OrderService", "UpdateAddress"));
            self.inner.unary(req, path, codec).await
        }
        /// 更新状态
        pub async fn update_status(
            &mut self,
            request: impl tonic::IntoRequest<super::UpdateStatusRequest>,
        ) -> std::result::Result<
            tonic::Response<super::super::resp::AffReply>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/order.OrderService/UpdateStatus",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("order.OrderService", "UpdateStatus"));
            self.inner.unary(req, path, codec).await
        }
        /// 更新价格
        pub async fn update_amount(
            &mut self,
            request: impl tonic::IntoRequest<super::UpdateAmountRequest>,
        ) -> std::result::Result<
            tonic::Response<super::super::resp::AffReply>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/order.OrderService/UpdateAmount",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("order.OrderService", "UpdateAmount"));
            self.inner.unary(req, path, codec).await
        }
        /// 完成支付
        pub async fn complete_pay(
            &mut self,
            request: impl tonic::IntoRequest<super::CompletePayRequest>,
        ) -> std::result::Result<
            tonic::Response<super::super::resp::AffReply>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/order.OrderService/CompletePay",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("order.OrderService", "CompletePay"));
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod order_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with OrderServiceServer.
    #[async_trait]
    pub trait OrderService: std::marker::Send + std::marker::Sync + 'static {
        /// 创建
        async fn create(
            &self,
            request: tonic::Request<super::Order>,
        ) -> std::result::Result<
            tonic::Response<super::super::resp::IdReply>,
            tonic::Status,
        >;
        /// 获取单条
        async fn get(
            &self,
            request: tonic::Request<super::super::req::IdRequest>,
        ) -> std::result::Result<tonic::Response<super::GetReply>, tonic::Status>;
        /// 列表
        async fn list(
            &self,
            request: tonic::Request<super::ListRequest>,
        ) -> std::result::Result<tonic::Response<super::ListReply>, tonic::Status>;
        /// 更新地址
        async fn update_address(
            &self,
            request: tonic::Request<super::UpdateAddressRequest>,
        ) -> std::result::Result<
            tonic::Response<super::super::resp::AffReply>,
            tonic::Status,
        >;
        /// 更新状态
        async fn update_status(
            &self,
            request: tonic::Request<super::UpdateStatusRequest>,
        ) -> std::result::Result<
            tonic::Response<super::super::resp::AffReply>,
            tonic::Status,
        >;
        /// 更新价格
        async fn update_amount(
            &self,
            request: tonic::Request<super::UpdateAmountRequest>,
        ) -> std::result::Result<
            tonic::Response<super::super::resp::AffReply>,
            tonic::Status,
        >;
        /// 完成支付
        async fn complete_pay(
            &self,
            request: tonic::Request<super::CompletePayRequest>,
        ) -> std::result::Result<
            tonic::Response<super::super::resp::AffReply>,
            tonic::Status,
        >;
    }
    #[derive(Debug)]
    pub struct OrderServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> OrderServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for OrderServiceServer<T>
    where
        T: OrderService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/order.OrderService/Create" => {
                    #[allow(non_camel_case_types)]
                    struct CreateSvc<T: OrderService>(pub Arc<T>);
                    impl<T: OrderService> tonic::server::UnaryService<super::Order>
                    for CreateSvc<T> {
                        type Response = super::super::resp::IdReply;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::Order>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as OrderService>::create(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = CreateSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/order.OrderService/Get" => {
                    #[allow(non_camel_case_types)]
                    struct GetSvc<T: OrderService>(pub Arc<T>);
                    impl<
                        T: OrderService,
                    > tonic::server::UnaryService<super::super::req::IdRequest>
                    for GetSvc<T> {
                        type Response = super::GetReply;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::super::req::IdRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as OrderService>::get(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/order.OrderService/List" => {
                    #[allow(non_camel_case_types)]
                    struct ListSvc<T: OrderService>(pub Arc<T>);
                    impl<T: OrderService> tonic::server::UnaryService<super::ListRequest>
                    for ListSvc<T> {
                        type Response = super::ListReply;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ListRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as OrderService>::list(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ListSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/order.OrderService/UpdateAddress" => {
                    #[allow(non_camel_case_types)]
                    struct UpdateAddressSvc<T: OrderService>(pub Arc<T>);
                    impl<
                        T: OrderService,
                    > tonic::server::UnaryService<super::UpdateAddressRequest>
                    for UpdateAddressSvc<T> {
                        type Response = super::super::resp::AffReply;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::UpdateAddressRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as OrderService>::update_address(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = UpdateAddressSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/order.OrderService/UpdateStatus" => {
                    #[allow(non_camel_case_types)]
                    struct UpdateStatusSvc<T: OrderService>(pub Arc<T>);
                    impl<
                        T: OrderService,
                    > tonic::server::UnaryService<super::UpdateStatusRequest>
                    for UpdateStatusSvc<T> {
                        type Response = super::super::resp::AffReply;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::UpdateStatusRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as OrderService>::update_status(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = UpdateStatusSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/order.OrderService/UpdateAmount" => {
                    #[allow(non_camel_case_types)]
                    struct UpdateAmountSvc<T: OrderService>(pub Arc<T>);
                    impl<
                        T: OrderService,
                    > tonic::server::UnaryService<super::UpdateAmountRequest>
                    for UpdateAmountSvc<T> {
                        type Response = super::super::resp::AffReply;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::UpdateAmountRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as OrderService>::update_amount(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = UpdateAmountSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/order.OrderService/CompletePay" => {
                    #[allow(non_camel_case_types)]
                    struct CompletePaySvc<T: OrderService>(pub Arc<T>);
                    impl<
                        T: OrderService,
                    > tonic::server::UnaryService<super::CompletePayRequest>
                    for CompletePaySvc<T> {
                        type Response = super::super::resp::AffReply;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::CompletePayRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as OrderService>::complete_pay(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = CompletePaySvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for OrderServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "order.OrderService";
    impl<T> tonic::server::NamedService for OrderServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
