// This file is @generated by prost-build.
/// 分页
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Paginate {
    /// 总记录数
    #[prost(uint32, tag = "1")]
    pub total: u32,
    /// 页码
    #[prost(uint32, tag = "2")]
    pub page: u32,
    /// 每页条数
    #[prost(uint32, tag = "3")]
    pub page_size: u32,
    /// 总页数
    #[prost(uint32, tag = "4")]
    pub total_page: u32,
}
/// 分页请求
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PaginateRequest {
    /// 页码
    #[prost(uint32, optional, tag = "1")]
    pub page: ::core::option::Option<u32>,
    /// 每页条数
    #[prost(uint32, optional, tag = "2")]
    pub page_size: ::core::option::Option<u32>,
}
