// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Shop {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub merchant_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub category_id: ::prost::alloc::string::String,
    /// 对应 BIGINT
    #[prost(int64, tag = "4")]
    pub deposit: i64,
    #[prost(string, tag = "5")]
    pub name: ::prost::alloc::string::String,
    #[prost(enumeration = "ShopKind", tag = "6")]
    pub kind: i32,
    #[prost(string, tag = "7")]
    pub description: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "8")]
    pub created_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(enumeration = "super::audit::AuditStatus", tag = "9")]
    pub status: i32,
    /// 存储为 JSON 字符串
    #[prost(message, optional, tag = "10")]
    pub meta: ::core::option::Option<ShopMeta>,
    /// 是否平台自营
    #[prost(bool, tag = "11")]
    pub is_platform_self_operated: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ShopMeta {
    /// 授权方 (如：品牌所有者/公司名)
    #[prost(string, tag = "1")]
    pub licensor: ::prost::alloc::string::String,
    /// 品牌名称
    #[prost(string, tag = "2")]
    pub brand_name: ::prost::alloc::string::String,
    /// 被授权方 (通常为当前商户公司名)
    #[prost(string, tag = "3")]
    pub licensee: ::prost::alloc::string::String,
    /// 授权有效期/期限 (建议使用 Timestamp 记录具体的截止日期)
    #[prost(message, optional, tag = "4")]
    pub expiry_date: ::core::option::Option<super::range::DateRange>,
    /// 授权起始日期/签署日期
    #[prost(message, optional, tag = "5")]
    pub authorization_date: ::core::option::Option<::prost_types::Timestamp>,
    /// 证明文件
    #[prost(string, repeated, tag = "6")]
    pub proof: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// 店铺审核
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ShopAudit {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub merchant_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub shop_id: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub auditor_id: ::prost::alloc::string::String,
    #[prost(enumeration = "super::audit::AuditStatus", tag = "5")]
    pub audit_status: i32,
    #[prost(string, tag = "6")]
    pub audit_comments: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "7")]
    pub audit_date: ::core::option::Option<::prost_types::Timestamp>,
}
/// 店铺类型
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ShopKind {
    /// 普通店
    Standard = 0,
    /// 官方旗舰店
    OfficialFlagship = 1,
    /// 旗舰店
    Flagship = 2,
    /// 卖场旗舰店
    MallFlagship = 3,
    /// 专卖店
    Specialty = 4,
    /// 专营店
    Franchise = 5,
}
impl ShopKind {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Standard => "Standard",
            Self::OfficialFlagship => "OfficialFlagship",
            Self::Flagship => "Flagship",
            Self::MallFlagship => "MallFlagship",
            Self::Specialty => "Specialty",
            Self::Franchise => "Franchise",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "Standard" => Some(Self::Standard),
            "OfficialFlagship" => Some(Self::OfficialFlagship),
            "Flagship" => Some(Self::Flagship),
            "MallFlagship" => Some(Self::MallFlagship),
            "Specialty" => Some(Self::Specialty),
            "Franchise" => Some(Self::Franchise),
            _ => None,
        }
    }
}
